# DB Access
mongodb:
  host: localhost
  port: 27017
  db: masaospace
  user: test
  password: test
  collection:
    user: user
    ticket: ticket
    file: file
    gamemetadata: gamemetadata
    gamedata: gamedata
    gamepast: gamepast
    mail: mail
    comment: comment
    series: series
    playlog: playlog
redis:
  host: localhost
  port: 6379
  db: 0
# file access
file:
  # path to store user-uploaded files
  path: /service-masao-space/uploaded-files
  # temporary directory
  temporary: /tmp
  # file id length
  idLength: 16
# file data
filedata:
  # max file size in bytes
  maxSize: 2097152
  # disk space per user (10MB)
  diskSpace: 1310720
  name:
    maxLength: 250
  description:
    maxLength: 1024
  # whitelist of mime types
  types:
    - image/bmp
    - image/jpeg
    - image/gif
    - image/png
    - image/svg+xml
    - audio/mpeg
    - audio/x-wav
    - audio/ogg

# web server config
webserver:
  port: 8080
  # connection is secure
  secure: false
  # external static files distribution
  externalstatic: false

# smtp config
smtp:
  # host of mail server
  host: "localhost"
  # port of mail server
  port: 587
  # whether initialize connection on TLS.
  secure: false


# service
service:
  name: "masao.space"
  url: "http://localhost:8080/"
  mail: "mail@localhost"
  # host name of service
  hostname: localhost
  domain: "localhost:8080"
  # host name of sandbox
  sandboxHostname: localhost
  sandboxDomain: "localhost:8080"

# logging
log:
  level: debug


# users
user:
  # internal id length
  idLength: 16
  # screen name
  screenName:
    minLength: 4
    maxLength: 24
  # display name
  name:
    maxLength: 64
  # password
  password:
    minLength: 6
    maxLength: 64
  # profile
  profile:
    maxLength: 1024
  # url
  url:
    maxLength: 1024





# sessions
session:
  # cookie secret
  secret: test
  # session TTL (in seconds)
  life: 864000

# tickets
ticket:
  # ticket length
  length: 16
  # ticket life 8in seconds)
  life: 86400

# games
game:
  title:
    maxLength: 30
  level:
    min: 0
    max: 10
  description:
    maxLength: 500
  tag:
    maxNumber: 10
    maxLength: 50
  script:
    maxLength: 102400

# comments
comment:
  maxLength: 10240

# series
series:
  name:
    maxLength: 64
  description:
    maxLength: 500

