# DB Access
mongodb:
  host: localhost
  port: 27017
  db: masaospace
  user: test
  password: test
  collection:
    user: user
    ticket: ticket
    file: file
redis:
  host: localhost
  port: 6379
  db: 0
# file access
file:
  # path to store user-uploaded files
  path: /home/no/masaopost/data
  # file id length
  idLength: 16

# web server config
webserver:
  port: 8080
  # connection is secure
  secure: false

# logging
log:
  level: debug


# users
user:
  # internal id length
  idLength: 16
  # screen name
  screenName:
    minLength: 4
    maxLength: 15
  # display name
  name:
    minLength: 1
    maxLength: 64
  # password
  password:
    minLength: 6
    maxLength: 64



# sessions
session:
  # cookie secret
  secret: test
  # session TTL (in seconds)
  life: 86400

# tickets
ticket:
  # ticket length
  length: 16
  # ticket life 8in seconds)
  life:
    setpassword: 86400
