# DB Access
mongodb:
  host: localhost
  port: 27017
  db: masaospace
  user: test
  password: test

  collection:
    user: user
redis:
  host: localhost
  port: 6379
  db: 0

# web server config
webserver:
  port: 8080
  # connection is secure
  secure: false

# logging
log:
  level: debug


# users
user:
  # internal id length
  idLength: 16

# sessions
session:
  # cookie secret
  secret: test
  # session TTL (in seconds)
  life: 86400
