# DB Access
mongodb:
  host: localhost
  port: 27017
  db: masaospace
  user: test
  password: test
  collection:
    user: user
    ticket: ticket
    file: file
    gamemetadata: gamemetadata
    gamedata: gamedata
    gamepast: gamepast
    mail: mail
    comment: comment
redis:
  host: localhost
  port: 6379
  db: 0
# file access
file:
  # path to store user-uploaded files
  path: /home/no/masaopost/data
  # file id length
  idLength: 16
# file data
filedata:
  name:
    maxLength: 250
  description:
    maxLength: 1024

# web server config
webserver:
  port: 8080
  # connection is secure
  secure: false

# service
service:
  name: MasaoSpace
  domain: localhost
  url: "http://localhost/"
  mail: "mail@localhost"

# logging
log:
  level: debug


# users
user:
  # internal id length
  idLength: 16
  # screen name
  screenName:
    minLength: 4
    maxLength: 24
  # display name
  name:
    maxLength: 64
  # password
  password:
    minLength: 6
    maxLength: 64
  # profile
  profile:
    maxLength: 1024




# sessions
session:
  # cookie secret
  secret: test
  # session TTL (in seconds)
  life: 86400

# tickets
ticket:
  # ticket length
  length: 16
  # ticket life 8in seconds)
  life: 86400

# games
game:
  title:
    maxLength: 30
  level:
    min: 0
    max: 10
  description:
    maxLength: 300

# comments
comment:
  maxLength: 10240

